- gatsby-node.js
- i18n/react-intl/en.json
- i18n/react-intl/fr.json
- i18n/react-intl/zh-CN.json
- v3/how-to-guides/02-pallet-design/g-loose-coupling/index.mdx
- v3/how-to-guides/index.mdx
This creates a top-level category view for How-to guides. I've removed the content that was there previously because that is covered in #122. 
Closes #106.
> Update How-to Guide landing page

- static/assets/tutorials/kitties-tutorial/02-create-kitties.rs
- static/assets/tutorials/kitties-tutorial/03-dispatchables-and-events.rs
- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
- static/assets/tutorials/kitties-tutorial/05-completed.rs
It seems like the following line is missed in examples files
```use scale_info::TypeInfo;```
it produces compilation errors.
> Missed line

- v3/tutorials/04-forkless-upgrades/index.mdx
I have changed the pallet-scheduler dependency from,
pallet-scheduler = { default-features = false, version = '3.0.0' }  // which was not working
to
[dependencies.pallet-scheduler]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-10'    // latest tag here.
version = '4.0.0-dev'
For me node-template was not compiling the project with the dependency defined in the docs, so I changed it and it's working fine now.
> Changed the dependency pallet-scheduler.

- v3/docs/07-advanced/b-scale-codec/index.mdx
Found a discrepancy while using `cScale` library, confirmed with `parity-scale-codec`:
```
let test_compact_32: u32 = 65535;
println!("Compact {} encoded = {:02X?}", test_compact_32, Compact(test_compact_32).encode());
```
```
Compact 65535 encoded = [FE, FF, 03, 00]
```
Polkadot address: 12uzeddBwDaBEb9Gny6Q6ySeAtfUuA4kucacrACgMT6YVNRA
> Fix SCALE compact example

- v3/docs/07-advanced/h-ss58/index.mdx
Refactor and polish of the page overall, it was missing most of the content in the [old wiki](https://gist.github.com/NukeManDan/1cc0958746815d625ee9f57e2930aea0) that has no other home and should live here. Missed in #105 
closes #114 
Outstanding items before done:
> Update ss58 page

- v3/docs/01-getting-started/c-installation/index.mdx
Remove the previous outdated advice and add  rosetta 2 requirement. See the discussion here: https://github.com/paritytech/substrate/issues/10203
> Update setup guide for Apple M1

- v3/docs/07-advanced/b-scale-codec/index.mdx
SCALE C++ implementation was recently moved to a new repo, hence the link should be updated.
> Update link to SCALE C++ implementation

- static/assets/tutorials/kitties-tutorial/02-create-kitties.rs
- static/assets/tutorials/kitties-tutorial/03-dispatchables-and-events.rs
- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
- static/assets/tutorials/kitties-tutorial/05-completed.rs
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
This PR updates several things around maintaining the Kitty tutorial, in the different repositories it touches. There's two main areas of updating: code on template branches and write-up here. 
[Front-end template](https://github.com/substrate-developer-hub/substrate-front-end-template/tree/tutorials/kitties) (code updates):
[Node template branch](https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/kitties) (code updates):
See [commits from Nov 9th, 2021](https://github.com/substrate-developer-hub/substrate-node-template/commits/tutorials/kitties).
See [commit](https://github.com/substrate-developer-hub/substrate-node-template/commit/23b0544b491a32b90d8c888d2827dc91befe3340).
Substrate docs (write-up):
> Kitty tutorial updates: new pallet declaration, removing types.json and updating write-up

- v3/docs/01-getting-started/e-glossary/index.mdx
- v3/docs/02-concepts/b-extrinsics/index.mdx
- v3/docs/03-runtime/h-weights-and-fees/index.mdx
Currently does not jump to wanted section because the anchor hash misses a traling `s`
> Anchor not working, misses trailing "s"

- package.json
make CI pass with `undefined` links
This is a PATCH that should be properly addressed before closing #552
> check link fix

- docs-sandbox/tutorials/02-simulate-network/index.mdx
I split the private network tutorial into two tutorials 
1) using the predefined accounts
2) generating keys and a chain spec
This PR covers the first one. 
I also felt the Polkadot-JS section was a distraction. I'll put that in a third tutorial.
> [sandbox] Split private network into two tutorials

- v3/tutorials/02-proof-of-existence/index.mdx
> [docs] typo

- v3/tutorials/03-permissioned-network/index.mdx
Template version `v3.0.0` can no longer build due to dependency issues. It should be bumped to the latest version.
I use the `monthly-2021-11` node template in the tutorial and it works well in general. 
But there is still another problem, `custom type mapping` can be no longer changed in polkadot.js apps as the developer page is gone. And the whole part that custom type mapping is no longer needed. I finished the rest of the tutorial even skipping that part. But I'm not sure if it should be deleted or have a further explanation. So I leave it with an issue (#583).
Also, fix a typo in the code snippet.
> Update permissioned-network template version to `monthly-2021-11`

- static/assets/tutorials/kitties-tutorial/01-basic-setup.rs
- static/assets/tutorials/kitties-tutorial/02-create-kitties.rs
- static/assets/tutorials/kitties-tutorial/03-dispatchables-and-events.rs
- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
- static/assets/tutorials/kitties-tutorial/05-completed.rs
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
Tested on latest node template `monthly-2021-11-1`.
- Fixes template code and adds instruction to use `serde` as a dependency. 
- Removes `#[pallet::generate_storage_info]` as not necessary for tutorial.
- Slight edits to template code to match style of previous ones each builds on.
> Kitties tutorial code fixes

- i18n/react-intl/en.json
- i18n/react-intl/fr.json
- i18n/react-intl/zh-CN.json
- src/components/DevNavMenu.tsx
- v3/how-to-guides/08-tools/d-subwasm/index.mdx
Initially planned to pack a couple tooling guides here but for now this covers Subwasm basics.
Open to ideas on adding or modifying current content. Tricky to reference any specific examples for this one because this is a tool that creates files to be checked locally.
> Add subwasm guide

- v3/tutorials/07-add-a-pallet/index.mdx
Typo fix in "Add the Nicks Pallet to your Runtime" tutorial
> Fixed typo in /07-add-a-pallet/index.mdx

- v3/tutorials/07-add-a-pallet/index.mdx
Reverts substrate-developer-hub/substrate-docs#613
> Revert "Fixed typo in /07-add-a-pallet/index.mdx"

- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
- v3/tutorials/03-permissioned-network/index.mdx
- v3/tutorials/04-forkless-upgrades/index.mdx
- v3/tutorials/06-node-metrics/index.mdx
- v3/tutorials/07-add-a-pallet/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
Closes #606 (as well as other items in #132). This also implies closing [this tracking issue](https://github.com/substrate-developer-hub/substrate-docs/issues/600).
The reason I used a separate tracking issue was because the work here updates the tutorial write-ups with relevant latest Substrate updates.  #600 helped me keep track of both the "docs" work and the "template update" work which I did synchronously. For the docs stuff here, updates included: 
- Updating all `git clone` commands to clone the latest node template at master (all at `monthly-2021-11-1`)
- Removing the need to specify custom types in Polkadot JS Apps UI
- Updating according to new pallet declaration in `construct_runtime!`
- No longer needing to specify `--tmp` when launching a chain
I've compiled and tested all …
> Update tutorials to latest monthly tag

- v3/docs/03-runtime/e-storage/index.mdx
- `get` extension for storage accessors has been removed
- `GenesisConfig` elements are not defined as  `Option`s
> Remove some FRAME v1 leftovers

- README.md
- v3/docs/02-concepts/d-transaction-pool/index.mdx
- v3/docs/02-concepts/g-execution/index.mdx
- v3/docs/02-concepts/h-off-chain-features/index.mdx
Hi team 👋
I found small improvements while going through the [Key Concepts](https://docs.substrate.io/v3/concepts/runtime) section.
Notes on changes:
- https://github.com/substrate-developer-hub/substrate-docs/commit/73a4675c50df36173dc5dd7de39ae4fff9796ec7
- I thought it should either be `nonce > 0` or `nonce >= 1` - I just chose the former
- https://github.com/substrate-developer-hub/substrate-docs/commit/4311fa1abad89b41dc5f5b29823e324d3fb6f634
- I was using node `v17.2.0` and was getting lots of errors on `yarn` and thought it was worth adding to README
> Small tidy up

- v3/tutorials/02-proof-of-existence/index.mdx
In the "Build a proof of existence dApp tutorial", the substrate template will not build with the snippet given, due to the line `#[pallet::generate_storage_info]`:
It builds with the line removed. The [working code example](https://github.com/substrate-developer-hub/substrate-node-template/blob/773d72752f3598e5d405b48c6f716f4153c95070/pallets/template/src/lib.rs) given at the end of the tutorial has this line removed.
> Broken code snippet (POE tutorial)

- v3/tutorials/03-permissioned-network/index.mdx
Updated what I believe are misspellings as I followed the guide.
On lines 513 to 516, the final sentence is confusingly worded to me but I am not sure what the original author intended for it. "If running node in a public internet, you need to otherwise put the reachable nodes as bootnodes of the Chain Spec.", sounds better to me but I might not understand what the statement is referencing correctly yet.
Got everything running though, great tutorial so thanks to everyone!
> Update index.mdx misspellings

- src/components/MainNav.tsx
This removes Community Resources menu item from global menu.
Reason: this page has been decommissioned
(https://substrate.io/ecosystem/resources/community-resources/)
> remove community resources link

- v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
Updating the tutorial documentation for [Connecting a Parachain](https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#start-the-collator-node) Adding the `bootnodes` parameter to collator node start command. This connects the embedded relay node to local relay chain so blocks will form on the parachain after registered and an epoch has passed.
Linked issue: https://github.com/substrate-developer-hub/substrate-docs/issues/707
> [Cumulus Tutorial] Fix collator block formation

- v3/tutorials/04-forkless-upgrades/index.mdx
- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
- v3/tutorials/08-ink-workshop/c-build-erc20-contract/index.mdx
Fixed typos in Smart Contracts turorial. 
In the forkless upgrade tutorial, I replaced frame_support::EqualPrivilegeOnly with frame_support::traits::EqualPrivilegeOnly, 
as frame_support::EqualPrivilegeOnly leads to an unresolved import error when trying to build the demo project.
> fixed typos

- v3/tutorials/05-private-network/index.mdx
Trying to execute as written without scheme provided leads to
substrate-node-template git:(tut5) ✗ ./target/release/node-template key insert --base-path /tmp/node01 \
--chain customSpecRaw.json \
--suri 0xSOMEKEY \
--password-interactive \
--key-type aura
error: The following required arguments were not provided:
--scheme <SCHEME>
USAGE:
node-template key insert --base-path <PATH> --chain <CHAIN_SPEC> --key-type <key-type> --password-interactive --scheme <SCHEME> --suri <suri> --tracing-receiver <RECEIVER>
For more information try --help
> Tut5: node-template key insert added mandatory --scheme

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
In the rest of the tutorial the getter `all_kitties_count` is not used
> fix storage getter name

- v3/tutorials/07-add-a-pallet/index.mdx
In response to this issue:
https://github.com/substrate-developer-hub/substrate-docs/issues/701
I see that the path is correct, but the runtime referred to is the substrate repository runtime and not the Developer Hub node template runtime. I modified the context to make this clearer.
> Change reference to Substrate repo

- v3/tutorials/05-private-network/index.mdx
The command could not be executed, so I fixed it.
> [docs] fix typo in commands (tutorials/05-private-network)

- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
After I removed these two lines, the build succeeded.
> Fix #747: [kitties-tutorial] File not found for module mock and tests

- v3/docs/03-runtime/e-storage/index.mdx
In the given example, generic parameter was specified without restricting but later on uses type parameter of that generic. This have generated error regarding associated type not found. Restricting this generic type however resolved the error.
> Fix error in example code of runtime storage documentation

- v3/tutorials/03-permissioned-network/index.mdx
- v3/tutorials/05-private-network/index.mdx
https://docs.substrate.io/tutorials/v3/permissioned-network/#obtaining-node-keys-and-peerids
Add 0x prefix to the hexadecimal peer ID
> [Tutorial: permissioned-network] Fix #760 Add 0x prefix to the hexadecimal peer ID

- v3/docs/07-advanced/a-account-info/index.mdx
I just went through [Advanced > Account Information](https://docs.substrate.io/v3/advanced/account-info/) and it looks great with minor typos.
Thanks team ❤️
> fix small typos for account info

- v3/docs/03-runtime/i-benchmarking/index.mdx
- v3/how-to-guides/03-weights/b-benchmarking/index.mdx
As of https://github.com/paritytech/substrate/pull/10771 `--json` is the new `--raw`
> --json is the new --raw

- static/assets/tutorials/ink-workshop/1.1-finished-code.rs
- static/assets/tutorials/ink-workshop/1.2-finished-code.rs
- static/assets/tutorials/ink-workshop/1.3-finished-code.rs
- static/assets/tutorials/ink-workshop/1.3-template.rs
- static/assets/tutorials/ink-workshop/1.4-finished-code.rs
- static/assets/tutorials/ink-workshop/1.4-template.rs
- static/assets/tutorials/ink-workshop/1.5-finished-code.rs
- static/assets/tutorials/ink-workshop/1.5-template.rs
- static/assets/tutorials/ink-workshop/1.6-finished-code.rs
- static/assets/tutorials/ink-workshop/1.6-template.rs
- static/assets/tutorials/ink-workshop/2.1-finished-code.rs
- static/assets/tutorials/ink-workshop/2.1-template.rs
- static/assets/tutorials/ink-workshop/2.2-finished-code.rs
- static/assets/tutorials/ink-workshop/2.2-template.rs
- static/assets/tutorials/ink-workshop/2.3-finished-code.rs
- static/assets/tutorials/ink-workshop/2.3-template.rs
- static/assets/tutorials/ink-workshop/2.4-finished-code.rs
- static/assets/tutorials/ink-workshop/2.4-template.rs
- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
- v3/tutorials/08-ink-workshop/b-develop-smart-contract/index.mdx
- v3/tutorials/08-ink-workshop/c-build-erc20-contract/index.mdx
In our most recent release of ink! we removed all storage collections with the exception
of `Mapping`. I won't get into the details here, but if you're curious you can go read
about it in the [ink! release notes](https://github.com/paritytech/ink/releases/tag/v3.0.0-rc9).
This PR updates the ink! workshop to use this new storage collection, and removes
references to the deprecated storage data structures.
> Update ink! tutorial for `v3.0.0-rc9`

- .yarnrc.yml
- Dockerfile
- package.json
- v3/how-to-guides/01-basics/a-pallet-integration/index.mdx
- v3/how-to-guides/02-pallet-design/g-loose-coupling/index.mdx
- v3/how-to-guides/03-weights/b-benchmarking/index.mdx
- v3/how-to-guides/04-ocw/a-transactions/index.mdx
- v3/how-to-guides/04-ocw/b-http-requests/index.mdx
- v3/how-to-guides/04-ocw/c-local-storage/index.mdx
- v3/how-to-guides/09-tools/a-integrate-try-runtime/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/03-permissioned-network/index.mdx
- v3/tutorials/04-forkless-upgrades/index.mdx
- v3/tutorials/07-add-a-pallet/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
We will use explicit polkadot release versions for now. This also removed some lingering issues with toml snippets and explicit versions called out that are not maintained.
> Updates to remove `devhub/latest` tag

- README.md
develop branch isn't used any more - we can just branch off main like normal now.
> remove reference to develop branch.

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
Ink tutorial was [updated](https://github.com/substrate-developer-hub/substrate-docs/commit/1dd2009b7c795d601d70a776feaa0c0722a85dce) for substrate v3, as well as [contract-node template](https://github.com/paritytech/substrate-contracts-node) in tag v0.7.0, but `substrate-contracts-node` installation command is still on tag v0.6.0
> Update substrate-contracts-node tag version

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
Change 'actually' to 'actual'.
> Fix typo in kitties tutorial

- v3/tutorials/05-private-network/index.mdx
Updating the live version with some content changes. I got it working all the way through finalization. The live version has both the predefined account keys and the generated keys, so not as tidy as the new version in progress in the `main-md `branch.
Change --raw to --json per:
https://github.com/substrate-developer-hub/substrate-docs/pull/850
> Update live private network with changes

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
fix no variant or associated item named `KittyExists` found for enum `pallet::Error` in the current scope
> fix pallet::Error KittyExists not found

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
Change words so then comments match exactly the variables they refer to.
> docs(kitties-tutorial): fix typo

- v3/docs/03-runtime/a-FRAME/index.mdx
- v3/docs/03-runtime/b-macros/index.mdx
`#[pallet::generate_storage_info]` is now defaulted.
> update pallet attr documentation

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
With the latest node template, if you paste the sp-io dependecy into pallet/template/cargo.toml you will get a "failed to load manifest for dependency" error. Incrementing the branch version from .17 to .18 fixed the issue for me. I have documented the fix here: https://stackoverflow.com/questions/70403605/failed-to-load-manifest-for-dependency/71786336#71786336
This fix will improve the tutorial experience, although it was a good learning experience for me to fix this issue :)
> Update sp-io cargo.toml dependency branch version

- package.json
- v3/docs/03-runtime/h-weights-and-fees/index.mdx
The tuple is required if more than one argument is specified. Looks like it was there once but maybe someone did not realise that the brackets were indeed supposed to be there.
> tuple notation fell off

- v3/docs/03-runtime/k-testing/index.mdx
> Update runtime -> testing `run_to_block` example

- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
- static/assets/tutorials/kitties-tutorial/05-completed.rs
The error is mentioned in the tutorial and referenced in the code, but missing from the enum in the template
> Add missing error type KittyExists to Error enum

- v3/docs/07-advanced/b-scale-codec/index.mdx
Hi! I've been working on [this SCALE Codec TS implementation](https://github.com/unstoppablejs/unstoppablejs/tree/main/packages/scale-ts#scale-ts) for the last 5 months and I think that now it's mature enough to be a worthy addition to the list of SCALE Codec implementations.
> Add `scale-ts` to the list of implementations

- v3/docs/03-runtime/m-upgrades/index.mdx
The label "D1-runtime-migration" is changed to "E1-runtimemigration".
> Update obsolete migration label and link

- v3/tutorials/07-add-a-pallet/index.mdx
I hope that this batch of changes i came up with while working through the Nicks Pallet Tutorial seem like straightforward improvements. A summary of the types of changes i did (i tried to thoroughly depict my rationale for individual changes in the commit comments):
- Addition or alteration of some words to improve clarity of instructions
- Updating of Balances code snippet where it referenced code that is not in the latest few iterations of `substrate-node-template` repo
- Fixing a few broken links
Please let me know if there's anything i need to change about this attempted contribution, thanks!
> Fixing dead links and some wording in `07-add-a-pallet` tutorial

- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
For building the node template on Debian/ubuntu/WSL the make package is required. The ttikv-jemalloc-sys v0.4.3+5.2.1-patched.2 crate now requires the make tool to compile itself and thus the node template. 
I have tested this with ubuntu 22.04 LTS and WSL2 on Windows 11.
> Additional build dependency for Debian/ubuntu/WSL

- v3/docs/01-getting-started/c-installation/index.mdx
Adds `make` based on many reports of it being needed on WSL2 and Ubuntu 22.04 LTS
> add make as dep

- content/md/en/docs/reference/how-to-guides/weights/add-benchmarks.md
InvArch had problems with copy-pasting from the [benchmarking example](https://docs.substrate.io/v3/runtime/benchmarking/#example).
` --extrinsic '\*'` leads to `Error: Input("No benchmarks found which match your input.")`
the correct is ` --extrinsic '*'`
duplicate of https://github.com/substrate-developer-hub/substrate-docs/pull/1052
> fix benchmarking command

- content/md/en/docs/reference/how-to-guides/weights/add-benchmarks.md
since https://github.com/paritytech/substrate/pull/11164 the benchmarking CLI has changed
now it needs to call `benchmark pallet` instead of just `benchmark`
> fix benchmarking subcommand

- content/md/en/docs/tutorials/get-started/trusted-network.md
`./target/release/node-template key insert --base-path /tmp/node01 \ --chain customSpecRaw.json \ --scheme Ed25519 \ --suri <your-secret-key> \ --password-interactive \ --key-type gran`
was throwing out:
```
error: Found argument ' --scheme' which wasn't expected, or isn't valid in this context
USAGE:
node-template key insert [OPTIONS] --key-type <KEY_TYPE> --scheme <SCHEME>
For more information try --help
```
So just removing backslashed fixed it.
> Fixing bash command because there was a problem with backlashes

- src/styles/tailwind-custom.css
Since the banner has inverted background colors from the site's general color modes, if there are any links in the banner text the link underline appears in the wrong/opposite colors. This is the fix for that.
> Correct link underline color in banner

- content/md/en/docs/tutorials/get-started/trusted-network.md
I delated a repeated line in the Add trusted node tutorial.
> Delete repetition in Add trusted node tutorial

- content/md/en/docs/tutorials/get-started/build-local-blockchain.md
Fix a closed bracket in the wrong place
> Fix link in Build local blockchain tutorial

- content/md/en/docs/tutorials/get-started/forkless-upgrade.md
Should use `compressed` wasm.
We also need to update the screenshot images.
> Should use `compressed` wasm.

- content/md/en/docs/tutorials/get-started/permissioned-network.md
Change `tag` with `branch` in the tutorial and set the line with the default order used in the template.
> Change tag with branch tutorial

- content/md/en/docs/main-docs/test/debug.md
> Fix h2 heading

- content/md/en/docs/tutorials/work-with-pallets/custom-pallet.md
https://substrate.stackexchange.com/questions/3855/use-macros-in-a-custom-pallet-tutorial-doesnt-compile
> delete `generate_storage_info` in tutorial

- README.md
Adding a note about our internal process for keeping our node template, tutorial write-ups and solutions up-to-date.
Not exactly sure where this should live but this feels ok for now. 
CC: @NukeManDan: step 3. needs a little more details. Can you add your edits in please? Just commit directly to this PR 😎 .
> Add note about devhub/latest tag

- content/md/en/docs/main-docs/fundamentals/accounts-addresses-keys.md
Added "by" to "This secret seed phrase can be used __ an account owner to recover access to an account if the private key is lost."
Removed the extra 'T' in the first word in "TIn addition to allowing you to derive multiple addresses from the same public key, base-58 encoding has the following benefits"
Removed an extra 'm' in command in "You can look the a chain-specific address for a public key using the subkey inspect commmand and --network option ot by using Subscan." I also think the sentence can be worded differently to convey its meaning.
> Correct typos in accounts-addresses-keys.md

- content/md/en/docs/main-docs/build/libraries.md
Change from "separate" to "separation" to correct the grammar.
> Correct typo in Introduction to libraries

- content/md/en/docs/main-docs/install/macos.md
- content/md/en/docs/main-docs/install/troubleshooting.md
As explained in #1324, developers on M1 machines are experiencing the following error when building blockchain locally:
`error: failed to run custom build command for prost-build v0.10.4`
This has become a very common issue for developers, so we should add it to the docs.
See e.g.
https://substrate.stackexchange.com/questions/3565/bulding-polkadot-release-v0-9-24-fails-while-compiling-a-dependency-prost-bui
Fixes #1324
> Add solution to local build errors on M1 machines

- content/md/en/docs/main-docs/install/troubleshooting.md
Add instructions for adding to PATH + fix typo :)
Missing out the PATH is a very common error we have seen blocking our students from getting set up with the quick start. Once spotted, it's a super simple fix but easy to overlook!
> Add instructions for adding to PATH

- content/md/en/docs/main-docs/build/tx-weights-fees.md
1.Change from "The custom weight calculation type must implement the follow traits" to "The custom weight calculation type must implement the following traits" 
2. I went through the DispatchInfo struct in weight.rs and it contains three traits as opposed to two traits specified in this documentation, so I corrected this.
> Fix typo in tx-weight-fees.md

- content/md/en/docs/main-docs/build/events-errors.md
> Small typo fix

- content/md/en/docs/tutorials/work-with-pallets/contracts-pallet.md
The pallet_contracts has a required associated type of [MaxStorageKeyLen](https://paritytech.github.io/substrate/master/pallet_contracts/pallet/trait.Config.html#associatedtype.MaxStorageKeyLen)
The method [get_storage](https://paritytech.github.io/substrate/master/pallet_contracts_rpc_runtime_api/trait.ContractsApi.html#method.get_storage) provided by the trait ContractsApi, expects its `key` to be a vector.
> Add missing type for  pallet_contracts and fix method parameter

- content/md/en/docs/main-docs/build/tx-weights-fees.md
1. Added glossary link at the end of Normal dispatches section
2. Added the correct link for inherents at the end of Mandatory dispatches section
> Added appropriate links to broken links

- content/md/en/docs/main-docs/build/chain-spec.md
I think "them" would be more appropriate than "then" in the context of this sentence... "When distributing chain specs in JSON format, you should distribute **them** in the raw format...."
> Fix typo in chain-spec.md

- content/md/en/docs/reference/frame-macros.md
With the deprecated `generate_storage_info` attribute now assumed by default, this updates our macro reference doc to note that an override may be used with caution.
> Update macro doc

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
There is a mistake in the branch version for the nicks pallet dependency, it shows "polkadot-v26" instead of "polkadot-v0.9.26"
> Fix error in add-a-pallet.md

- content/md/en/docs/tutorials/work-with-pallets/specify-the-origin-for-a-call.md
Change from "identifies" to "identified" and "xplains" to "explain"
> Fix typo in specify-the-origin-for-a-cal.md

- content/md/en/docs/fundamentals/index.md
Updated the "runtime development" hyperlink from `/fundamentals/runtime-intro` to `/fundamentals/runtime-development/`
> Update the broken link for runtime development

- content/md/en/docs/fundamentals/why-substrate.md
A minor typo and what appears to be one linked section too many I found while reading through the documentation.
> Fix why-substrate typos

- content/md/en/docs/fundamentals/accounts-addresses-keys.md
change `https://datatracker.ietf.org/doc/id/draft-msporny-base58-01.html` to `https://datatracker.ietf.org/doc/html/draft-msporny-base58-01`
> Fix broken URL for base-58 encoding

- content/md/en/docs/fundamentals/offchain-operations.md
From context of offchain section in the doc,  I think need to change `offline` to `offchain`
> Fix typo: offline

- content/md/en/docs/tutorials/connect-other-chains/local-parachain.md
The repo of https://github.com/substrate-developer-hub/substrate-parachain-template/tree/polkadot-v0.9.26 , the built binary is `parachain-template-node` not `parachain-collator` This can lead to misunderstandings among newcomers
> Fix wrong binary name

- content/md/en/docs/tutorials/smart-contracts/build-a-token-contract.md
fn `transfer_from_to` 's `from` and `to` parameters are not borrowed types
> Fix wrong ink! code

- content/md/en/docs/tutorials/get-started/authorize-specific-nodes.md
Minor optimisation suggestion, feel free to ignore if not appropriate.
Adds the `--release` flag to `cargo check` commands to re-use the built artifacts from `cargo build --release` in the previous section(s). It just prevents a full debug build of the project on the first cargo check.
> add --release option to cargo check

- content/md/en/docs/tutorials/get-started/authorize-specific-nodes.md
The Polkadot/Substrate Portal defaults to Polkadot the first time the portal is used. An instruction step is missing in the `Authorize access for the third node` section to switch to the local node as per the screenshot included in the documentation beneath it. This proposed change would auto select the local node, but it may be better to add a step on how to manually switch.
PS - the url was simply copied from the result of doing the switch manually.
> auto-select local node in portal

- content/md/en/docs/tutorials/get-started/authorize-specific-nodes.md
Following the guide, my third node on localhost was unable to automatically connect to the local testnet due to local firewall blocking all incoming connections (https://substrate.stackexchange.com/a/1657). A suggestion is to add a small hint/reminder here which may be helpful.
> add local firewall note

- content/md/en/docs/tutorials/smart-contracts/develop-a-smart-contract.md
All other data types in the sentence were lower case so suggest 'boolean' as well.
> typo corrections

- content/md/en/docs/tutorials/smart-contracts/build-a-token-contract.md
- compiler warned about unnecessary parentheses around method argument so removed to avoid warning
> typo corrections and formatting

- content/md/en/docs/tutorials/smart-contracts/prepare-your-first-contract.md
cargo-contract 1.5.0 does seem to require specific nightly versions. Everything works if you use this set of commands with nightly-2022-08-15:
```
rustup toolchain install nightly-2022-08-15
rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-15
rustup component add rust-src --toolchain nightly-2022-08-15
cargo +nightly-2022-08-15 contract build
```
Released SE answer: https://substrate.stackexchange.com/questions/4785/errore0158-when-testing-default-contract-from-flipper
> Flipper contract Update and test

- content/md/en/docs/tutorials/connect-relay-and-parachains/acquire-a-testnet-slot.md
I had problems producing parachain blocks due to simply *adding* my public key to the existing default session keys in generated file, rather than *replacing* the session keys. The instruction says "Add" but the code snippet only shows a single key, which I missed unfortunately. Based on https://substrate.stackexchange.com/a/179/3138 (3.), it seems a running collator is required for each configured key before blocks will be produced, so an additional note may be especially useful, as going through the whole process of requesting a slot, syncing the relay chain, only to find you've made a small mistake is rather time consuming.
PS - I may have gotten something else wrong, but I am now producing blocks by simply launching the additional missing collators for the other default session keys.
> clarify session keys requirement

- content/md/en/docs/reference/command-line-tools/polkadot-apps.md
The page currently links to https://polkadot.js.org/apps instead of https://polkadot.js.org/docs
This PR fixes this link
> Fix link to polkadotjs docs

- content/md/en/docs/reference/scale-codec.md
Add the implementation from Parity of typescript SCALE in the links provided at the end of the page
> Add TS Scale implementation in the links

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
Updated nicks and balances pallet trait implementations to be compatible with the new version as per recent upgrade: v0.9.30.
> Update: trait impl types for nicks and balances

- content/md/en/docs/tutorials/smart-contracts/prepare-your-first-contract.md
`dylint-link` is a wrapper around Rust's default linker (cc) to help create Dylint libraries. Required for the current tutorial.
> Added instruction to download crate dylint-link

- content/md/en/docs/test/unit-testing.md
I noticed that it was quite hard to find information on how to test for event emission, and the best resources were just stackoverflow posts that were fairly hard to find. As such, I added this documentation and also added an example of testing for an event to the node template.
Related PR on the node template: paritytech/substrate#12722.
> Add documentation of event unit testing

- content/md/en/docs/tutorials/collectibles-workshop/01-prepare.md
> Fix broken link to "Get oriented" section in "Prepare a working environment" section

- content/md/en/docs/tutorials/collectibles-workshop/05-add-storage-items.md
> Fix "State transitions and storage" link in "Add custom storage items" section in collectibles workshop

- content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-transactions.md
The [Make offchain transactions How-to-Guide](https://docs.substrate.io/reference/how-to-guides/offchain-workers/offchain-transactions/) is outdated, and also missing some details.
This PR fixes it.
> update offchain-transactions how-to-guide

- content/md/en/docs/build/runtime-storage.md
The multi-key storage maps subsection is missing a link reference for the crate documentation and a wrong markdown syntax.
> Fix missing link and markdown syntax in build/runtime-storage

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
The text references the type of `Balances` to be `u128` which is not clear from the above code example: 
> For example, this `impl` block configures the Balances pallet to use the `u128` type to track balances.
The missing `Balances` type is defined here: [https://github.com/substrate-developer-hub/substrate-node-template/blob/904f7679273c40ebead46de4f047a7eaf24e1017/runtime/src/lib.rs#L64](https://github.com/substrate-developer-hub/substrate-node-template/blob/904f7679273c40ebead46de4f047a7eaf24e1017/runtime/src/lib.rs#L64)
> Correct code example to include `Balance` type `u128`

- content/md/en/docs/tutorials/connect-relay-and-parachains/connect-a-local-parachain.md
- content/md/en/docs/tutorials/connect-relay-and-parachains/prepare-a-local-relay-chain.md
At PBA2 we attempted to run the first two tutorials in the section "Connect Relay and Parachains" as an exercise. This revealed issues with outdated version numbering, non-unique protocol ids, and confusion about prerequisites. Thus, this bundle of fixes.
> Fixing Issues Discovered at PBA2

- content/md/en/docs/reference/scale-codec.md
The Ruby library that is linked to in the docs has been deprecated and archived in favor of a newer implementation.
This change just changes the reference to point to the currently supported version for Ruby.
> Fix the URL for the Ruby SCALE codec implementation

- content/md/en/docs/reference/address-formats.md
We have a very complete reference of implementations for Base58 on our page about Base58, which is very useful for anyone coming at the Substrate ecosystem from another language, or for anyone who wants to see how things work at a low level, but we are lacking the same set of resources for our SS58 checksumming / address format implementation.
This list is probably incomplete, but it has the 4 most-complete implementations that I have found so far outside of the Substrate and Polkadot-js core implementations, and I think it could be useful, just like the Base58 list, for anyone looking at our ecosystem from outside of it, particularly if they are not Rust programmers, as our docs and our code for our Rust SS58 implementation are pretty dense.
> Add some links to some SS58 implementations.

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
The link to the contracts-pallet page is broken, as it was removed a few weeks ago. This commit replaces that broken link with a link to the smart-contracts tutorial, instead.
> Replace the broken link with a different contracts tutorial.

- content/md/en/docs/build/chain-spec.md
The page that explains state and storage changed URLs without a redirect in place, so this link became broken. This fixes it.
> Fix the link to the page that explains the Substrate storage trie.

- content/md/en/docs/build/runtime-storage.md
The how-to for minting basic tokens was removed, but this link to it was missed.
> This how-to was removed, but this link to it was missed.

- content/md/en/docs/test/simulate-parachains.md
Issue fixed:
- Removed duplicate of the entire article
- Fixed broken links
- Line 179: Fixed relative directory path (binaries are NOT in substrate-parachain-template folder)
- Line 244, 250: Fixed deprecated statement (up-to-date version is snake_case instead of camelCase and has no 'S' at the end)
- Line 268: Fixed typo
- Line 285: Fixed erroneous statement (it's called "xcmPallet" in Polkadot.js portal, not "polkadotXcm", at least in Rocococ testnet)
Question for further improvement:
* Explain or fix indentation in config.toml
* What part of config.toml does [[hrmp_channel]] belong? Shall it be in [relaychain] section? 
* (SUGGESTION) It would be cool to see complete final versions of the files changed in the tutorials, as an attachment or something - similar to what they usually do …
> [FIX] Update simulate-parachains.md

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
Update: 
Earlier:  pallet-nicks = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.35" } 
Proposed change: pallet-nicks = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
Fixing the error : "error: duplicate lang item in crate `sp_io` (which `sp_application_crypto` depends on): `panic_impl`." caused by earlier dependency.
> update add-a-pallet for pallet_nicks crate

- content/md/en/docs/tutorials/smart-contracts/build-a-token-contract.md
- content/md/en/docs/tutorials/smart-contracts/develop-a-smart-contract.md
- content/md/en/docs/tutorials/smart-contracts/prepare-your-first-contract.md
- content/md/en/docs/tutorials/smart-contracts/use-maps-for-storing-values.md
`cargo contract test` was replaces with `cargo test` in https://github.com/paritytech/cargo-contract/pull/958
> Replace `cargo contract test` with `cargo test`

- content/md/en/docs/tutorials/smart-contracts/develop-a-smart-contract.md
The address was incorrectly copied from a previous step.
> Fix address used in SC tutorial

- content/md/en/docs/tutorials/work-with-pallets/use-macros-in-a-custom-pallet.md
Currently, the [Use macros in a custom pallet](https://docs.substrate.io/tutorials/work-with-pallets/use-macros-in-a-custom-pallet/) has a deprecation warning because `revoke_claim` and `create_claim` do not have the `pallet::call_index` attribute defined. This pull request removes that deprecation warning by adding the `call_index` attribute to each.
> Fix deprecation warning in tutorial

- content/md/en/docs/tutorials/work-with-pallets/specify-the-origin-for-a-call.md
Fixes one typo inside the [tutorial](https://docs.substrate.io/tutorials/work-with-pallets/specify-the-origin-for-a-call/).
> Fix typo in Specify Origin for a Call tutorial

- content/md/en/docs/tutorials/connect-relay-and-parachains/connect-a-local-parachain.md
Corrects event name to match accompanying image.
> docs: fix typo

- content/md/en/docs/tutorials/smart-contracts/build-a-token-contract.md
- Removed warning messages in the code snippets
- Typo fix to refer to the `total_supply` in the right markdown formatting
- Use the `$INSTANTIATED_CONTRACT_ADDRESS` placeholder to reduce confusion
- Add reference to instruction on how to instantiate the contract node for ease
- Removed an unnecessary instruction to look at the `Cargo.toml` file, which didn't have any follow-up action associated with it
> Various fixes to the Build a token contract tutorial

- content/md/en/docs/tutorials/integrate-with-tools/integrate-a-light-client-node.md
Updates this PR makes include:
- I’ve removed the background information about light clients and how Substrate connect works because it came off as a little too much information, which I can access [here](https://docs.substrate.io/fundamentals/light-clients-in-substrate-connect/) anyways. We should probably follow-up with a review of the Light clients in Substrate Connect page and ensure nothing is lost (there also seems to be duplicate content in there which is covered by this tutorial).  See issue #1901. 
- We don’t use the Substrate Connect browser extension so I’ve removed references to that.
- The intro now explicitly states that we’ll be connecting to Statemint in this tutorial, and objectives revised accordingly.
- The code snippet for connecting to Statemint was throwing errors …
> Update light client tutorial

- content/md/en/docs/quick-start/modify-the-runtime.md
Fixed typo in the link of "Explore the code".
> Fixed typo in link

- content/md/en/docs/reference/command-line-tools/subxt.md
- content/md/en/docs/tutorials/build-application-logic/use-macros-in-a-custom-pallet.md
- content/md/en/docs/tutorials/integrate-with-tools/integrate-a-light-client-node.md
Requires #2028 for all checks to pass
> Fix styles

- content/md/en/docs/test/simulate-parachains.md
The new repo doesn't have the branch release-v1.0.0, I have seen people having issues with that in StackExchange: 
- https://substrate.stackexchange.com/questions/9839/cant-start-test-network-using-zombienet-macos
-  https://substrate.stackexchange.com/questions/9981/what-version-of-polkadot-relaychain-and-substrate-parachain-template-can-be-used
The options I see are: 
1. Use `git clone https://github.com/paritytech/polkadot` to the old repo
2.  Don’t do the `git checkout release-v1.0.0 `and keep the user in master branch
3.  Update everything to work with the version `release-v1.1.0`
My fix uses the option 2, but feel free to suggest the fix to one you consider better.
> Fix wrong branch of new repository

- content/md/en/docs/test/set-up-a-test-network.md
The arguments need underscore in stead of capital letters (reference: https://substrate.stackexchange.com/questions/9364/debugging-zombienet-config-after-using-hrmp-channels)
> Update hrmp commands zombienet

- content/md/en/docs/build/build-process.md
- content/md/en/docs/tutorials/build-application-logic/use-macros-in-a-custom-pallet.md
The default runtime template assumes the pallet-template exposes a weightinfo config.
This introduces that into the tutorial so that users do not need to go into the runtime and delete things
> More Proof of Existence Fixes

- content/md/en/docs/reference/how-to-guides/pallet-design/incorporate-randomness.md
```rust
Self::BlockNumber
```
```rust
BlockNumberFor<Self>
```
> Change "Self::BlockNumber" to "BlockNumberFor<Self>"

- content/md/en/docs/learn/accounts-addresses-keys.md
- content/md/en/docs/learn/transaction-lifecycle.md
> Improved english?

- content/md/en/docs/build/origins.md
companion to https://github.com/paritytech/polkadot-sdk/pull/3362
> deprecate origin page

- content/md/en/docs/reference/xcm-reference.md
The xcm reference page holds outdated information that is now up-to-date in the rust docs.
This is part of the plan to move our documentation to rust docs.
> Add deprecated banner to xcm reference and link to rust docs

- README.md
- config/menus.js
- config/siteMetadata.js
- config/webConsts.js
- content/locales/en/menus.json
- example.env.development
- example.env.production
The marketplace content is unmaintained so it should no longer be featured on the Substrate docs.
> Remove all links to Substrate Marketplace

- content/md/en/docs/tutorials/integrate-with-tools/explore-sidecar-endpoints.md
Update Postman Collection link so that it includes the full docs (path params, query params, etc) in all the endpoints.
- [Previous Postman Documentation](https://documenter.getpostman.com/view/24602305/2s8YsqWaj8#intro) has no info on each endpoint. Example : [Account Asset Approvals](https://documenter.getpostman.com/view/24602305/2s8YsqWaj8#431e27f8-b902-4fc5-b9bc-fa8aadf9c0bf)
- [New Postman Link](https://documenter.getpostman.com/view/21393319/2sA3Qs9C9M#intro) includes all the necessary info and are aligned and up to date with the [OpenAPI](https://paritytech.github.io/substrate-api-sidecar/dist/) docs of Sidecar. Example : [Account Asset Approvals](https://documenter.getpostman.com/view/21393319/2sA3Qs9C9M#6205139b-8865-432f-ac2b-d4733101fd35) …
> Update Postman docs link in explore-sidecar-endpoints.md

- content/md/en/docs/learn/runtime-development.md
- content/md/en/docs/reference/frame-macros.md
- content/md/en/docs/tutorials/collectibles-workshop/03-create-pallet.md
Removes some old and wrong stuff from the pallet tutorial, see: https://github.com/paritytech/polkadot-sdk/issues/5171  
Given that this is to be deprecated soon anyway, i only did the minimal changes and added a warning.
> Remove wrong stuff from minimal-pallet tut

- content/md/en/docs/tutorials/integrate-with-tools/explore-sidecar-endpoints.md
Added a deprecation banner in the Sidecar tutorial page pointing to the Sidecar docs, the README and the guides folder.
> Deprecation banner in Sidecar tutorial page

- .netlify/_redirects
- content/config/nav.yaml
- content/md/en/docs/build/genesis-configuration.md
- content/md/en/docs/build/origins.md
- content/md/en/docs/build/pallet-coupling.md
- content/md/en/docs/build/remote-procedure-calls.md
- content/md/en/docs/examples/quickstart/index.html
- content/md/en/docs/learn/offchain-operations.md
- content/md/en/docs/learn/runtime-development.md
- content/md/en/docs/polkadot-sdk/index.md
- content/md/en/docs/reference/frame-macros.md
- content/md/en/docs/reference/how-to-guides/offchain-workers/index.md
- content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-http-requests.md
- content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-indexing.md
- content/md/en/docs/reference/how-to-guides/offchain-workers/offchain-local-storage.md
- content/md/en/docs/reference/how-to-guides/pallet-design/use-loose-coupling.md
- content/md/en/docs/reference/how-to-guides/pallet-design/use-tight-coupling.md
- content/md/en/docs/reference/xcm-reference.md
- content/md/en/docs/tutorials/build-application-logic/add-offchain-workers.md
- content/md/en/docs/tutorials/collectibles-workshop/03-create-pallet.md
- content/md/en/docs/tutorials/integrate-with-tools/explore-sidecar-endpoints.md
- content/md/en/homepage/get-started-homepage.md
- content/md/en/homepage/get-technical-homepage.md
- content/md/en/homepage/hands-on-homepage.md
- src/pages/index.js
- src/styles/scss/_home.scss
- src/templates/single.js
- static/assets/quickstart/index.html
This takes a big step towards deprecating a lot of the content here. 
Everything is still accessible, no URL has changed, but you would have to first see the deprecation page. 
The docs homepage now looks like this: 
Once you click on it, you land on this page with further explanation, and access to all the old content in the navbar: 
And a single page looks like this:
> Meta Depreaction

- content/md/en/docs/build/smart-contracts-strategy.md
Replacing small typo on [Smart Contracts Strategy](https://docs.substrate.io/build/smart-contracts-strategy/)
> Fix small typo on smart contract docs
