- gatsby-node.js
- i18n/react-intl/en.json
- i18n/react-intl/fr.json
- i18n/react-intl/zh-CN.json
- src/components/DevNavMenu.tsx
- v3/docs/06-tools/0-landing-page/index.mdx
- v3/docs/06-tools/a-subkey/index.mdx
- v3/docs/06-tools/b-memory-profiling/index.mdx
> Add landing page for Tools section

- src/styles/tailwind-preset.css
- fixes dark mode stacks BGs
- cleans up global css between stacks
> Fix dark mode html BG

- src/components/layout/homepage/ExploreDocs.tsx
- src/pages/index.tsx
- src/pages/playground.tsx
Minor edits. Removed parachains under "Ways to Build" until we have the content from #150.
> Review homepage

- src/pages/tutorials/v3.tsx
@sacha-l I reorder tuts in the tut index page in the order which I think a Substrate learner should follow. Though it is just a a recommended order, I still think it is better to be ordered.
> Reorder tuts

- src/templates/htg-template.tsx
- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
> Fixed typo  & completed proofread tut - Create your first Substrate chain

- src/components/DevNavMenu.tsx
- src/components/DocsComponents/BottomButtons.tsx
- v3/tutorials/10-frontier-workshop/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Addressing #147 
- Updating Tuts link structure. (Please note: only use hashlink (#somelink) instead of a full link in DevNavMenu
- Hiding BottomButtons on Frontier Tutorial. 
- Updated Logic for BottomButtons to account for hashlinks.
> Updated tuts link structure + bottom buttons logic

- gatsby-config.js
- package.json
- src/components/Hooks/use-site-metadata.tsx
- src/components/SEO.tsx
- yarn.lock
In anticipation of going public soon, adding sitemap and simple-analytics (cookie-less) plugins and setup.
> Added sitemap and analytics plugin

- src/components/DevNavMenu.tsx
- src/components/DocsComponents/FastTrackPlayground.tsx
- src/pages/tutorials/v3.tsx
- v3/tutorials/07-add-a-pallet/index.mdx
> Proofread tut - add a pallet

- v3/docs/03-runtime/k-testing/index.mdx
> Proofread kb:runtime:testing

- v3/tutorials/10-frontier-workshop/index.mdx
port https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1144
> frontier patch

- gatsby-config.js
- gatsby-node.js
- src/components/DevNavMenu.tsx
- src/components/DocsComponents/NextButton.tsx
- src/components/DocsNav.tsx
- src/components/DocsNavMobile.tsx
- src/templates/doc-template.tsx
- src/templates/htg-template.tsx
- src/templates/tut-template.tsx
- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/03-permissioned-network/index.mdx
- v3/tutorials/04-forkless-upgrades/index.mdx
- v3/tutorials/05-private-network/index.mdx
- v3/tutorials/06-node-metrics/index.mdx
- v3/tutorials/07-add-a-pallet/index.mdx
- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
- v3/tutorials/08-ink-workshop/b-develop-smart-contract/index.mdx
- v3/tutorials/08-ink-workshop/c-build-erc20-contract/index.mdx
- v3/tutorials/09-cumulus/a-start-relay/index.mdx
- v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
- v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
- v3/tutorials/09-cumulus/d-rococo/index.mdx
- v3/tutorials/10-frontier-workshop/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
**MIGHT BREAK THINGS - NEED MORE 👀**
> WIP - Gatsby Node Updates

- .editorconfig
- v3/docs/01-getting-started/e-glossary/index.mdx
- v3/docs/02-concepts/h-off-chain-features/index.mdx
- Tweaks on content
- Oracle in glossary
- Off-chain updates
- Call out recipes links explicitly (cc @sacha-l should we backlog these to get into HTGs in a new issue?)
> Oracles and Offchain

- v3/docs/03-runtime/b-macros/index.mdx
> [docs] fix small typo issue 474

- v3/how-to-guides/01-basics/a-pallet-integration/index.mdx
There was a formatting problem with the Note.
> [docs] Pallet integration formatting fix (minor)

- .github/ISSUE_TEMPLATE/broken-link.yaml
- .github/ISSUE_TEMPLATE/bug-template-code.yaml
- .github/ISSUE_TEMPLATE/bug-template-site.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/content-template.yaml
- .github/ISSUE_TEMPLATE/feedback-template.yaml
Minor tweaks to make issue templates better.
Fixes issues with them not getting labels assigned (as we added emoji to them :rocket: )
> Tweak issue template, fix labels to be added

- .netlify/_redirects_develop
- .netlify/_redirects_production
- src/components/DevNavMenu.tsx
- v3/docs/07-advanced/d-block-import/index.mdx
This PR fixes some issues tagged with the "broken-link" label. See commit history.
> Fix broken links

- .netlify/_redirects_develop
- .netlify/_redirects_production
> fix 505, 440

- package.json
- v3/docs/02-concepts/d-transaction-pool/index.mdx
- v3/docs/07-advanced/h-ss58/index.mdx
- v3/how-to-guides/01-basics/a-pallet-integration/index.mdx
- v3/how-to-guides/01-basics/b-instantiable-pallets/index.mdx
- v3/how-to-guides/01-basics/c-constants/index.mdx
- v3/how-to-guides/01-basics/d-genesis-config/index.mdx
- v3/how-to-guides/01-basics/e-custom-chainspec/index.mdx
- v3/how-to-guides/01-basics/e-helper-functions/index.mdx
- v3/how-to-guides/01-basics/f-mint-token/index.mdx
- v3/how-to-guides/01-basics/g-weights/index.mdx
- v3/how-to-guides/02-pallet-design/a-add-contracts-pallet/index.mdx
- v3/how-to-guides/02-pallet-design/c-randomness/index.mdx
- v3/how-to-guides/03-weights/b-benchmarking/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
> Fix formatting, *confirm* prettier to work, hack to fix link checker

- package.json
- v3/docs/02-concepts/d-transaction-pool/index.mdx
- v3/docs/07-advanced/h-ss58/index.mdx
- v3/how-to-guides/01-basics/a-pallet-integration/index.mdx
- v3/how-to-guides/01-basics/b-instantiable-pallets/index.mdx
- v3/how-to-guides/01-basics/c-constants/index.mdx
- v3/how-to-guides/01-basics/d-genesis-config/index.mdx
- v3/how-to-guides/01-basics/e-custom-chainspec/index.mdx
- v3/how-to-guides/01-basics/e-helper-functions/index.mdx
- v3/how-to-guides/01-basics/f-mint-token/index.mdx
- v3/how-to-guides/01-basics/g-weights/index.mdx
- v3/how-to-guides/02-pallet-design/a-add-contracts-pallet/index.mdx
- v3/how-to-guides/02-pallet-design/c-randomness/index.mdx
- v3/how-to-guides/03-weights/b-benchmarking/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Reverts substrate-developer-hub/substrate-docs#528
> Revert "Fix formatting, *confirm* prettier to work, hack to fix link checker"

- v3/docs/07-advanced/b-scale-codec/index.mdx
> Add cScale to SCALE implementation list

- package.json
> check link fix (#553)

- docs-sandbox/docs/03-design/index.mdx
- docs-sandbox/docs/05-design/index.mdx
> Add a Design section 

- v3/how-to-guides/07-parachains/d-runtime-upgrades/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Updating `sandbox` for #565 followup, found more issues, should be all set now!
> format fixes from sandbox

- docs-sandbox/tutorials/03-private-network/index.mdx
This is split out private network tutorial. Everything except finalization worked for me. If someone can try troubleshooting, that would be awesome.
> [sandbox] Add revised private network tutorial

- docs-sandbox/docs/01-why-substrate/index.mdx
Placeholder but no content yet.
> [sandbox] Add Why Substrate (Vision) bucket and index.mdx file

- docs-sandbox/quickstart/index.mdx
> [sandbox] Add Quick start index.mdx placeholder

- v3/tutorials/07-add-a-pallet/index.mdx
not sure what the link should be...
> [docs] Update missing link

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
Updated the Kitties documentation page to use monthly-2021-11-1.
> Updated Kitties tutorial to use monthly-2021-11-1

- i18n/react-intl/en.json
- src/components/DevNavMenu.tsx
- v3/how-to-guides/07-parachains/a-solo-to-parachain/index.mdx
- v3/tutorials/09-cumulus/a-start-relay/index.mdx
- v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
- v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
- v3/tutorials/09-cumulus/d-rococo/index.mdx
> Cumulus updates and new content

- v3/tutorials/02-proof-of-existence/index.mdx
Closes #509 , #594 and #597.
Checks:
> PoE tutorial fixes

- v3/docs/06-tools/a-subkey/index.mdx
- update subkey to OSPL rule
- style changes
- Removed duplicated warnings
- fix internal links
**no new content, so I will go ahead an merge this as is**
> Subkey tweaks for style, fix links

- v3/docs/07-advanced/h-ss58/index.mdx
> 35 bit SS58

- src/components/Banner.tsx
- tailwind-preset.js
address #632 by adding -z-10 value to tailwind config
> Banner Bug

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
update installation versions for   
+ cargo-contract
+ contracts-node
> Update `cargo-contract` and `contracts-node` versions

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
"Oftentimes" is one word. "Often times" (two words), means something entirely different.
Ex:
"Often, times change faster than the people who live in them."
https://www.grammar.com/oftentimes_vs._often_times
I know this sounds nit-picky.
> Grammar fix 11-kitties-workshop/a-kitties-node/

- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
> Fix tutorials write-ups

- v3/how-to-guides/08-tools/d-subwasm/index.mdx
Improvements based on Chevdor's feedback.
> Add nitpicks

- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
We need first cd into the folder and then use 'git checkout' command
> Fix false instruction in git repo check out

- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Small grammar & typo fixes in /tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
> Kitties Grammar & Typo Fixes

- v3/docs/01-getting-started/a-overview/index.mdx
- v3/docs/01-getting-started/c-installation/index.mdx
- v3/docs/03-runtime/d-chain-specs/index.mdx
- v3/docs/03-runtime/g-events-and-errors/index.mdx
- v3/how-to-guides/01-basics/f-mint-token/index.mdx
- v3/how-to-guides/02-pallet-design/a-add-contracts-pallet/index.mdx
- v3/how-to-guides/07-parachains/a-solo-to-parachain/index.mdx
- v3/tutorials/01-create-your-first-substrate-chain/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/03-permissioned-network/index.mdx
- v3/tutorials/04-forkless-upgrades/index.mdx
- v3/tutorials/06-node-metrics/index.mdx
- v3/tutorials/07-add-a-pallet/index.mdx
- v3/tutorials/09-cumulus/a-start-relay/index.mdx
- v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
- v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
- Fix MD formatting for continued lists, supersedes #663 
- Remove proper nouns for templates
> Fix formatting, no template proper nouns

- v3/docs/06-tools/a-subkey/index.mdx
Corrected Schnorr signatures typo
> Typo update index.mdx

- v3/docs/07-advanced/h-ss58/index.mdx
Update SS58 checksum hash algorithm name and link with algorithm OID for Blake2b-512
> Update SS58 documentation hash algorithm and formats

- v3/tutorials/04-forkless-upgrades/index.mdx
Replaced instances of "schedular" with "scheduler"
> Corrected Typos

- src/components/DevNavMenu.tsx
> Fix typo so correct page gets displayed

- src/components/Hooks/use-site-metadata.tsx
Fixing graphql query for footer broken links 
- Terms
- Privacy
[Notion Page](https://www.notion.so/paritytechnologies/Substrate-Docs-Footer-Broken-Link-c18ca40bcee54c4aa02b266cf6608980)
> Footer Broken Links

- v3/how-to-guides/08-parachains/d-runtime-upgrades/index.mdx
Fix for a link wrongly formatted
> Fix link formatting

- v3/tutorials/05-private-network/index.mdx
https://docs.substrate.io/tutorials/v3/private-network/#enable-other-participants-to-join
Add missed --scheme in Step 5 and Step 6
> Fix #758 Add missed --scheme in #enable-other-participants-to-join

- v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Fix `Unhandled Rejection (TypeError): api.query.substrateKitties.multi is not a function`.
> Fixed correct method calls

- v3/tutorials/07-add-a-pallet/index.mdx
- broken link fixed
- small typo
> Fix link and typo

- v3/how-to-guides/02-pallet-design/g-loose-coupling/index.mdx
- v3/how-to-guides/03-weights/b-benchmarking/index.mdx
- v3/how-to-guides/04-ocw/a-transactions/index.mdx
- v3/how-to-guides/04-ocw/b-http-requests/index.mdx
- v3/how-to-guides/04-ocw/c-local-storage/index.mdx
- v3/how-to-guides/09-tools/a-integrate-try-runtime/index.mdx
- v3/tutorials/02-proof-of-existence/index.mdx
- v3/tutorials/07-add-a-pallet/index.mdx
> move to `devhub/latest` tag throughout, no use of monthly tags

- v3/docs/03-runtime/b-macros/index.mdx
- v3/docs/03-runtime/d-chain-specs/index.mdx
- v3/docs/03-runtime/e-storage/index.mdx
Hi team, just bringing in small tidy-ups as I was going through these docs.
Thanks ❤️
> Small tidy-ups on runtime docs

- v3/tutorials/05-private-network/index.mdx
> minor typo

- v3/tutorials/04-forkless-upgrades/index.mdx
> Fix minor typo

- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
> Fix minor typos in Substrate Kitties Tutorial

- content/config/nav.yaml
- content/md/en/docs/main-docs/index.md
- content/md/en/docs/tutorials/get-started/build-local-blockchain.md
- content/md/en/docs/tutorials/get-started/simulate-network.md
- content/md/en/docs/tutorials/get-started/trusted-network.md
- content/md/en/docs/tutorials/index.md
First pass at moving the mkdocs navigation (with some changes) into the Gatsby branch.
It would be nice to make all collections collapsible.
> Left navigation fleshed out for scaffolding

- content/md/en/docs/quick-start/quickstart.md
Moving from the mkdocs sandbox.
> Add quick start section to scaffolding

- content/md/en/docs/main-docs/install/index.md
- content/md/en/docs/main-docs/install/linux.md
- content/md/en/docs/main-docs/install/macos.md
- content/md/en/docs/main-docs/install/other-tools.md
- content/md/en/docs/main-docs/install/rust-builds.md
- content/md/en/docs/main-docs/install/troubleshooting.md
- content/md/en/docs/main-docs/install/windows.md
Moved WIP from mkdocs install section to this branch.
> Installation section WIP

- src/components/site/Newsletter.js
Adding a disclaimer if newsletter submission fails.
> Newsletter Disclaimer (for ad-blockers)

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
I forgot to delete something in https://github.com/substrate-developer-hub/substrate-docs/pull/829
we will have a new UX for this functionality, docs will be updated when it's ready
> Remove old text

- content/md/en/docs/main-docs/build/tx-weights-fees.md
- content/md/en/docs/reference/glossary.md
I think this fits in the Build section.
> Add weights and fees to build, add weight to glossary

- v3/docs/03-runtime/k-testing/index.mdx
I think adding a section about events testing can be useful.
> Add doc example for how to test events

- content/md/en/docs/tutorials/get-started/trusted-network.md
> remove purge step, add --password-interactive, finalizing blocks successfully

- v3/docs/03-runtime/j-debugging/index.mdx
Closes #838 
I searched the docs and only found problems with this one file.
> Fixing print macro in snippets

- v3/docs/03-runtime/j-debugging/index.mdx
> main update #852

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
> Upgrade `cargo-contract` and `substrate-contracts-node`

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
> Upgrade to `substrate-contracts-node` `v0.10.0`

- v3/how-to-guides/02-pallet-design/d-simple-crowdfund/index.mdx
This is going to need a bit of work. There is a pretty large leap between the knowledge expectations of the Randomness  How-To and this one. I'm going to need some assistance figuring out which files are being edited with the code snippets. 
@sacha-l
> [docs] Simple Crowdfund rework

- v3/tutorials/02-proof-of-existence/index.mdx
This PR solves (#884) by adding a pallet template (`lib.rs`) that compiles and also has all the `TODO`s that will be updated by the next steps in the tutorial.
@NukeManDan let me know if I got the idea correctly.
> [PoE] Adding initial template that compiles.

- static/assets/tutorials/kitties-tutorial/02-create-kitties.rs
- static/assets/tutorials/kitties-tutorial/03-dispatchables-and-events.rs
- static/assets/tutorials/kitties-tutorial/04-interacting-functions.rs
- static/assets/tutorials/kitties-tutorial/05-completed.rs
- v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
https://substrate.stackexchange.com/questions/1551/typeerror-api-query-substratekitties-countforkitties-is-not-a-function
> Fix count for kitties

- v3/docs/03-runtime/a-FRAME/index.mdx
It looks like "type" keyword is missed here
> Update runtime > Frame > skeleton of a pallet code block index.mdx

- src/components/Layout.tsx
- src/components/layout/homepage/DocCard.tsx
- src/pages/index.tsx
- src/styles/tailwind-custom.css
- src/styles/tailwind-preset.css
Notion: https://www.notion.so/paritytechnologies/Docs-Home-horizontal-scrolling-dc5847c3e92742749cfb6dd5a726db66
> Fix Home page scrolling issues

- src/components/MainNav.tsx
Merge together with Square One.
> Add Square One to menu

- v3/docs/01-getting-started/c-installation/index.mdx
> pkg-config needed for ubuntu 22

- content/md/en/docs/tutorials/work-with-pallets/custom-pallet.md
Mirroring https://github.com/substrate-developer-hub/substrate-docs/pull/966
> [main-md] update templateModule code

- src/components/MainNav.tsx
[Notion ticket](https://www.notion.so/paritytechnologies/Past-Seminars-page-a7beaef438db418ab683aaecafb2716a)
> Add Past Seminars to menu

- content/md/en/docs/main-docs/fundamentals/architecture.md
* Clarified some language
* Briefly mentioned runtime API and host function
* Removed mention of "Native Runtime"
> Rework Architecture page

- v3/tutorials/04-forkless-upgrades/index.mdx
Closes #1003 in `main`, see #1028
> close #1003

- v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
> close #949

- .netlify/_redirects
- src/components/MainNav.tsx
- v3/docs/07-advanced/h-ss58/index.mdx
- v3/tutorials/06-node-metrics/index.mdx
[Notion ticket](https://www.notion.so/paritytechnologies/Awesome-Substrate-link-to-GH-0b577406872848a88a7e95c64f83e4de)
> Update Awesome Substrate links and redirect

- v3/tutorials/06-node-metrics/index.mdx
https://substrate.stackexchange.com/questions/2738/error-reading-prometheus-post-https-localhost9090-api-v1-query-dial-tcp
> fix https in metrics issue

- content/md/en/docs/main-docs/build/build-process.md
Review on the build process doc.
> Close #1014

- src/components/site/Banner.js
[Notion task](https://www.notion.so/paritytechnologies/Temporarily-update-the-popup-on-substrate-io-with-hackathon-content-e6b92475754a4aeb95a66bf7a232512d)
> Add hackathon banner

- src/components/MainNav.tsx
[Notion task](https://www.notion.so/paritytechnologies/Smart-Contracts-ed2a04b17aa74d78bf4c1fbc68ddf9f0)
> Add Smart Contracts to menu

- content/md/en/docs/main-docs/install/linux.md
- content/md/en/docs/main-docs/install/macos.md
- content/md/en/docs/main-docs/install/windows.md
- update install needing protobuf-compiler for all systems
- clone depth 1 for template
> Install updates

- v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
Correct chain specs path for both relay chain and parachains
> Fix chain specs path

- v3/tutorials/02-proof-of-existence/index.mdx
The code for templateModule gives an runtime error (api connection, same issue : #558). The last version:
"https://github.com/substrate-developer-hub/substrate-front-end-template/blob/main/src/TemplateModule.js" works fine.
> Update templateModule front end code example

- content/md/en/docs/main-docs/test/benchmark.md
- content/md/en/docs/reference/command-line-tools/try-runtime.md
- content/md/en/docs/tutorials/get-started/trusted-network.md
all bash code blocks can be copied & pasted correctly into a bash shell
> Fix `bash` code blocks

- content/config/nav.yaml
- content/md/en/docs/main-docs/build/upgrade.md
- content/md/en/docs/main-docs/fundamentals/offchain-operations.md
- content/md/en/docs/main-docs/fundamentals/transaction-types.md
- content/md/en/docs/reference/command-line-tools/index.md
- content/md/en/docs/reference/command-line-tools/subflood.md
- content/md/en/docs/reference/command-line-tools/try-runtime.md
- content/md/en/docs/reference/how-to-guides/basics/configure-genesis-state.md
- content/md/en/docs/reference/how-to-guides/basics/customize-a-chain-specification.md
- content/md/en/docs/reference/how-to-guides/basics/mint-basic-tokens.md
- content/md/en/docs/reference/how-to-guides/consensus-models/create-a-hybrid-node.md
- content/md/en/docs/reference/how-to-guides/pallet-design/incorporate-randomness.md
- content/md/en/docs/reference/how-to-guides/testing/set-up-basic-tests.md
- content/md/en/docs/reference/how-to-guides/weights/add-benchmarks.md
- content/md/en/docs/reference/how-to-guides/weights/calculate-fees.md
- package.json
Pruned check links life used with `^.*├───OK─── .*$\n` regex mated and removed lines:
<details>
<summary> Log file (click to expand) </summary>
```
$ /home/dan/git/docs/node_modules/.bin/blc --filter-level=3 -rof --requests=10 --exclude=/localhost:8000 --exclude=/localhost:8100 --exclude=undefined http://localhost:9000/quick-start/
Getting links from: http://localhost:9000/quick-start/
└───OK─── https://cloudcdn-img.com/static/sbs/spacer.gif
Finished! 96 links found. 48 excluded. 0 broken.
Getting links from: http://localhost:9000/
Finished! 64 links found. 62 excluded. 0 broken.
Getting links from: http://localhost:9000/main-docs/
Finished! 99 links found. 86 excluded. 0 broken.
Getting links from: http://localhost:9000/tutorials/
Finished! 98 links found. 89 excluded. 0 broken.
Getting …
```
> link fixes, regex remove OK lines

- content/md/en/docs/tutorials/smart-contracts/develop-contract.md
- content/md/en/docs/tutorials/smart-contracts/erc20-token.md
- content/md/en/docs/tutorials/smart-contracts/first-smart-contract.md
- content/md/en/docs/tutorials/smart-contracts/index.md
The app is now available at https://contracts-ui.substrate.io
> Update Contracts UI URL

- gatsby-config.js
- package.json
- yarn.lock
This is a PR to add in a robots.txt file for search engines.
> add gatsby plugin for robots.txt

- content/md/en/docs/main-docs/build/pallet-coupling.md
- content/md/en/docs/main-docs/build/upgrade.md
- content/md/en/docs/tutorials/work-with-pallets/index.md
Signed-off-by: linning <linningde25@gmail.com>
> Fix some typos

- content/md/en/docs/tutorials/get-started/forkless-upgrade.md
Change polkadot-vv0.9.24 to polkadot-v0.9.24
> Typo in Upgrade a running network tutorial

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
To reflect changes made to the latest Substrate Template Node
> Update Nicks Pallet Tutorial

- content/md/en/docs/tutorials/work-with-pallets/contracts-pallet.md
You need to run the `cargo check -p node-template` to check the new code in `node/src/rpc.rs` file.
> Fix code in "Configure the contracts pallet" tutorial

- README.md
Reverts substrate-developer-hub/substrate-docs#636
> Revert "Add note about devhub/latest tag"

- src/components/site/NavLegal.js
Addresses [web issue #5](https://github.com/paritytech/web/issues/5)
> Replace footer Stack Overflow link with Stack Exchange

- content/md/en/docs/tutorials/work-with-pallets/custom-pallet.md
Another tag issue replaced with branch notation.
> Fix tag with branch

- content/md/en/docs/main-docs/fundamentals/node-and-network-types.md
Change from "and serving data is response to user requests." to "and serving data in response to user requests."
> Correct typo under full node section

- content/md/en/docs/main-docs/fundamentals/consensus.md
- content/md/en/docs/main-docs/fundamentals/transaction-types.md
- content/md/en/docs/main-docs/fundamentals/why-substrate.md
It is still in draft. I'll work through the rest of the doc by weekend and update it if I encounter other typos. After which I'll turn it to ready from draft PR
> Typos fixes

- content/md/en/docs/reference/how-to-guides/pallet-design/add-contracts-pallet.md
- content/md/en/docs/tutorials/smart-contracts/index.md
https://github.com/substrate-developer-hub/substrate-docs/pull/1044/files
This was mainly trying to pull the changes from the archived main into the new main, but I made some text and link changes, so a sanity check is in order.
> Integrate changes from resolved issue and PR 1044

- content/md/en/docs/reference/how-to-guides/tools/use-try-runtime.md
https://github.com/substrate-developer-hub/substrate-docs/pull/1036/files
https://github.com/substrate-developer-hub/substrate-docs/pull/1044/files
> [try-runtime] Integrate merged PR 1044 / 1036 into new main

- content/md/en/docs/main-docs/fundamentals/node-and-network-types.md
> Small typo fix

- content/md/en/docs/main-docs/build/randomness.md
Change from "required" to "requires" to fit the context.
> Fix tense in randomness.md

- content/md/en/docs/main-docs/build/custom-pallets.md
Change from "import" to "important"
> Fix typo in custom-pallets.md

- content/md/en/docs/main-docs/build/upgrade.md
Change from "communication to communicate"
> Fix typo in upgrade.md

- content/md/en/docs/build/upgrade.md
> Remove redundent word `label`

- content/md/en/docs/reference/command-line-tools/try-runtime.md
Links are fixed but the content still has issues.
> [try-runtime] Fix broken links

- content/md/en/docs/build/events-errors.md
Remove repeated words from initial sentence
> Fix initial sentence

- content/md/en/docs/fundamentals/node-and-network-types.md
"you should purge the full node then restart it as an archive mode" should be "you should purge the full node then restart it as an archive *node*"
> Fix typo "mode" => "node"

- content/md/en/docs/tutorials/get-started/upgrade-a-running-network.md
Note: the additional space between '4.' and 'Add' affected indentation and numbering.
> typo corrections

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
As with https://github.com/substrate-developer-hub/substrate-docs/pull/1529
> add --release option to cargo check

- content/md/en/docs/tutorials/smart-contracts/prepare-your-first-contract.md
Image currently shows as "<Image is missing>", updated path as per working image lower down.
> fix broken image

- content/md/en/docs/tutorials/smart-contracts/use-maps-for-storing-values.md
> minor correction

- .netlify/_redirects
As per https://github.com/substrate-developer-hub/substrate-docs/issues/1557
> add redirects for parachain tutorial

- content/md/en/docs/tutorials/work-with-pallets/use-macros-in-a-custom-pallet.md
Self explanatory, this has changed here https://github.com/paritytech/substrate/pull/11981
> Update Event to RuntimeEvent in the Config

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
> Version update

- content/md/en/docs/install/macos.md
> Update macos installation instructions

- content/md/en/docs/tutorials/connect-relay-and-parachains/prepare-a-local-relay-chain.md
> tutorial: Add note about getting nodes to find each other

- README.md
- content/md/en/docs/reference/how-to-guides/tools/create-a-txwrapper.md
- content/md/en/docs/reference/how-to-guides/tools/use-sidecar.md
- content/md/en/docs/reference/how-to-guides/tools/use-try-runtime.md
- content/md/en/docs/reference/how-to-guides/tools/verify-wasm.md
> Fix: typos

- content/md/en/docs/tutorials/work-with-pallets/use-macros-in-a-custom-pallet.md
instead of just copy pasting a code, add a sentence with with a small exercise and help for the reader
> encourage reader to implement code themselves

- content/md/en/docs/tutorials/work-with-pallets/add-a-pallet.md
for readers who might have missed it
> Insert link to howto install front-end template

- content/md/en/docs/tutorials/integrate-with-tools/integrate-a-light-client-node.md
Update the example code based on [breaking changes of polkadot-js/api](https://github.com/polkadot-js/api/releases/tag/v9.11.1)
> Update integrate-a-light-client-node.md tutorial

- content/md/en/docs/tutorials/collectibles-workshop/05-add-storage-items.md
Adding a space and capitalizing a T letter
> Adding a space and capitalizing the first letter

- content/md/en/docs/tutorials/integrate-with-tools/explore-sidecar-endpoints.md
A few improvement suggestions based on my review.
> Review sidecar tutorial

- content/md/en/docs/fundamentals/light-clients-in-substrate-connect.md
Add description of Substrate Connect extension to explain correctly how it works
> Update substrate connect extension

- content/md/en/docs/tutorials/smart-contracts/develop-a-smart-contract.md
Resolves #1914 
Maintain the failing tests in the tutorial flow but explain why the tests are failing at those particular steps in the process.
> Address failing tests issue in Develop a Smart Contract tutorial

- content/md/en/docs/reference/how-to-guides/storage-migrations/basic-storage-migration.md
Close opened rust code block in "basic-storage-migration.md"
> Close code block

- content/md/en/docs/install/linux.md
Fixed the network and node link issue. #1989
> Updated an incorrect link in the linux.md file with the right one.  #1989

- content/md/en/docs/build/genesis-configuration.md
Updated runtime genesisconfig instances with RuntimeGeneisConfig.
> 1996 update examples and tutorials mentioning genesisconfig

- content/md/en/docs/reference/scale-codec.md
- Added flutter lib for decoding/encoding SCALE codec
- Sorted the libs alphabetically
> Add dart lib

- content/md/en/docs/build/tx-weights-fees.md
syntax highlight is not correct with current code, let's fix the code
> Fix rust code in order to fix syntax highlight

- content/md/en/docs/reference/command-line-tools/subkey.md
this wasn't changed to cd to the new git repository before running the build command
> Update subkey.md cd to new directory
